# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aproxime_cracha.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aproxime_cartao(object):
    def setupUi(self, Aproxime_cartao):
        Aproxime_cartao.setObjectName("Aproxime_cartao")
        Aproxime_cartao.resize(1290, 841)
        Aproxime_cartao.setMinimumSize(QtCore.QSize(1290, 841))
        Aproxime_cartao.setMaximumSize(QtCore.QSize(1290, 841))
        Aproxime_cartao.setStyleSheet("background-color: rgb(255, 255, 255);")
        Aproxime_cartao.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Aproxime_cartao)
        self.centralwidget.setObjectName("centralwidget")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 731))
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(224, 227, 229);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_insira_cracha = QtWidgets.QLabel(self.centralwidget)
        self.label_insira_cracha.setGeometry(QtCore.QRect(50, 30, 1191, 211))
        self.label_insira_cracha.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 42pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 207, 0);")
        self.label_insira_cracha.setObjectName("label_insira_cracha")
        self.label_cartao = QtWidgets.QLabel(self.centralwidget)
        self.label_cartao.setGeometry(QtCore.QRect(70, 320, 151, 101))
        self.label_cartao.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.label_cartao.setText("")
        self.label_cartao.setPixmap(QtGui.QPixmap("imagens/Cartao.png"))
        self.label_cartao.setScaledContents(True)
        self.label_cartao.setObjectName("label_cartao")
        self.label_imagem_leitor = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_leitor.setGeometry(QtCore.QRect(70, 60, 151, 151))
        self.label_imagem_leitor.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 44pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 207, 0);")
        self.label_imagem_leitor.setText("")
        self.label_imagem_leitor.setPixmap(QtGui.QPixmap("imagens/Leitor.png"))
        self.label_imagem_leitor.setScaledContents(True)
        self.label_imagem_leitor.setObjectName("label_imagem_leitor")
        self.botao_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_registrar.setGeometry(QtCore.QRect(140, 580, 241, 131))
        self.botao_registrar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 26pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(0, 136, 74);")
        self.botao_registrar.setObjectName("botao_registrar")
        self.botao_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cancelar.setGeometry(QtCore.QRect(900, 580, 241, 131))
        self.botao_cancelar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 26pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 207, 0);")
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.lineEdit_tag_cartao = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tag_cartao.setGeometry(QtCore.QRect(240, 300, 991, 141))
        self.lineEdit_tag_cartao.setStyleSheet("border-style: inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.lineEdit_tag_cartao.setObjectName("lineEdit_tag_cartao")
        self.label_fundo_tag = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_tag.setGeometry(QtCore.QRect(50, 290, 1200, 161))
        self.label_fundo_tag.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.label_fundo_tag.setText("")
        self.label_fundo_tag.setObjectName("label_fundo_tag")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo.raise_()
        self.label_insira_cracha.raise_()
        self.label_imagem_leitor.raise_()
        self.botao_registrar.raise_()
        self.botao_cancelar.raise_()
        self.label_fundo_tag.raise_()
        self.label_cartao.raise_()
        self.lineEdit_tag_cartao.raise_()
        self.Label_Borda.raise_()
        Aproxime_cartao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Aproxime_cartao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Aproxime_cartao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Aproxime_cartao)
        self.statusbar.setObjectName("statusbar")
        Aproxime_cartao.setStatusBar(self.statusbar)

        self.retranslateUi(Aproxime_cartao)
        QtCore.QMetaObject.connectSlotsByName(Aproxime_cartao)

    def retranslateUi(self, Aproxime_cartao):
        _translate = QtCore.QCoreApplication.translate
        Aproxime_cartao.setWindowTitle(_translate("Aproxime_cartao", "MainWindow"))
        self.label_insira_cracha.setText(_translate("Aproxime_cartao", "            INSIRA O CRACHÁ DO USUÁRIO \n"
"                        SOBRE O LEITOR"))
        self.botao_registrar.setText(_translate("Aproxime_cartao", "REGISTRAR"))
        self.botao_cancelar.setText(_translate("Aproxime_cartao", "CANCELAR"))
        self.lineEdit_tag_cartao.setText(_translate("Aproxime_cartao", "                  TAG DO CARTÃO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aproxime_cartao = QtWidgets.QMainWindow()
    ui = Ui_Aproxime_cartao()
    ui.setupUi(Aproxime_cartao)
    Aproxime_cartao.show()
    sys.exit(app.exec_())
