# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aviso_liberacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aviso_Liberacao(object):
    def setupUi(self, Aviso_Liberacao):
        Aviso_Liberacao.setObjectName("Aviso_Liberacao")
        Aviso_Liberacao.resize(1290, 841)
        Aviso_Liberacao.setMinimumSize(QtCore.QSize(1290, 841))
        Aviso_Liberacao.setMaximumSize(QtCore.QSize(1290, 841))
        Aviso_Liberacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Aviso_Liberacao)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1270, 760))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_Atencao = QtWidgets.QLabel(self.frame)
        self.label_Atencao.setGeometry(QtCore.QRect(410, 10, 451, 121))
        self.label_Atencao.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 65pt \"Bosch Sans Bold\";")
        self.label_Atencao.setObjectName("label_Atencao")
        self.botao_relatar_problema = QtWidgets.QPushButton(self.frame)
        self.botao_relatar_problema.setGeometry(QtCore.QRect(770, 590, 281, 131))
        self.botao_relatar_problema.setStyleSheet("background-color: rgb(255, 207, 0);\n"
"border-style: outset;\n"
"border-radius: 35px;\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"\n"
"font: 75 30pt \"Bosch Sans Bold\";")
        self.botao_relatar_problema.setObjectName("botao_relatar_problema")
        self.label_texto = QtWidgets.QLabel(self.frame)
        self.label_texto.setGeometry(QtCore.QRect(10, 110, 1241, 221))
        self.label_texto.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";")
        self.label_texto.setObjectName("label_texto")
        self.botao_voltar = QtWidgets.QPushButton(self.frame)
        self.botao_voltar.setGeometry(QtCore.QRect(210, 590, 281, 131))
        self.botao_voltar.setStyleSheet("background-color: rgb(255, 207, 0);\n"
"border-style: outset;\n"
"border-radius: 35px;\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";")
        self.botao_voltar.setObjectName("botao_voltar")
        self.label_seguranca = QtWidgets.QLabel(self.frame)
        self.label_seguranca.setGeometry(QtCore.QRect(205, 330, 351, 90))
        self.label_seguranca.setStyleSheet("border-style: outset;\n"
"background-color: rgb(237, 0, 7);\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"\n"
"font: 75 30pt \"Bosch Sans Bold\";")
        self.label_seguranca.setAlignment(QtCore.Qt.AlignCenter)
        self.label_seguranca.setObjectName("label_seguranca")
        self.label_itens_seguranca = QtWidgets.QLabel(self.frame)
        self.label_itens_seguranca.setGeometry(QtCore.QRect(550, 330, 501, 90))
        self.label_itens_seguranca.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.label_itens_seguranca.setAlignment(QtCore.Qt.AlignCenter)
        self.label_itens_seguranca.setObjectName("label_itens_seguranca")
        self.label_meio_ambiente = QtWidgets.QLabel(self.frame)
        self.label_meio_ambiente.setGeometry(QtCore.QRect(205, 414, 351, 90))
        self.label_meio_ambiente.setStyleSheet("border-style: outset;\n"
"background-color: rgb(55, 162, 100);\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"\n"
"font: 75 28pt \"Bosch Sans Bold\";")
        self.label_meio_ambiente.setAlignment(QtCore.Qt.AlignCenter)
        self.label_meio_ambiente.setObjectName("label_meio_ambiente")
        self.label_itens_meio_ambiente = QtWidgets.QLabel(self.frame)
        self.label_itens_meio_ambiente.setGeometry(QtCore.QRect(550, 414, 501, 90))
        self.label_itens_meio_ambiente.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.label_itens_meio_ambiente.setAlignment(QtCore.Qt.AlignCenter)
        self.label_itens_meio_ambiente.setObjectName("label_itens_meio_ambiente")
        self.label_Atencao.raise_()
        self.label_texto.raise_()
        self.botao_voltar.raise_()
        self.botao_relatar_problema.raise_()
        self.label_seguranca.raise_()
        self.label_itens_seguranca.raise_()
        self.label_meio_ambiente.raise_()
        self.label_itens_meio_ambiente.raise_()
        Aviso_Liberacao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Aviso_Liberacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Aviso_Liberacao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Aviso_Liberacao)
        self.statusbar.setObjectName("statusbar")
        Aviso_Liberacao.setStatusBar(self.statusbar)

        self.retranslateUi(Aviso_Liberacao)
        QtCore.QMetaObject.connectSlotsByName(Aviso_Liberacao)

    def retranslateUi(self, Aviso_Liberacao):
        _translate = QtCore.QCoreApplication.translate
        Aviso_Liberacao.setWindowTitle(_translate("Aviso_Liberacao", "MainWindow"))
        self.label_Atencao.setText(_translate("Aviso_Liberacao", "ATENÇÃO"))
        self.botao_relatar_problema.setText(_translate("Aviso_Liberacao", "RELATAR\n"
"PROBLEMA"))
        self.label_texto.setText(_translate("Aviso_Liberacao", "<html><head/><body><p align=\"center\">O(s) seguinte(s) item(ns) não foram marcado(s), o que </p><p align=\"center\">significa que ele(s) apresenta(m) não conformidade:</p></body></html>"))
        self.botao_voltar.setText(_translate("Aviso_Liberacao", "VOLTAR"))
        self.label_seguranca.setText(_translate("Aviso_Liberacao", "SEGURANÇA:"))
        self.label_itens_seguranca.setText(_translate("Aviso_Liberacao", "1,2,3,4,"))
        self.label_meio_ambiente.setText(_translate("Aviso_Liberacao", "MEIO-AMBIENTE:"))
        self.label_itens_meio_ambiente.setText(_translate("Aviso_Liberacao", "1,2,3,4,"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aviso_Liberacao = QtWidgets.QMainWindow()
    ui = Ui_Aviso_Liberacao()
    ui.setupUi(Aviso_Liberacao)
    Aviso_Liberacao.show()
    sys.exit(app.exec_())
