# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editar_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editar_cadastro(object):
    def setupUi(self, Editar_cadastro):
        Editar_cadastro.setObjectName("Editar_cadastro")
        Editar_cadastro.resize(1290, 841)
        Editar_cadastro.setMinimumSize(QtCore.QSize(1290, 841))
        Editar_cadastro.setMaximumSize(QtCore.QSize(1290, 841))
        Editar_cadastro.setStyleSheet("background-color: rgb(255, 255, 255);")
        Editar_cadastro.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Editar_cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 731))
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(224, 227, 229);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.botao_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cancelar.setGeometry(QtCore.QRect(970, 590, 230, 120))
        self.botao_cancelar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 25pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 207, 0);")
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.botao_atualizar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_atualizar.setGeometry(QtCore.QRect(85, 590, 230, 120))
        self.botao_atualizar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 25pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(0, 136, 74);")
        self.botao_atualizar.setObjectName("botao_atualizar")
        self.botao_alterar_tag_cartao = QtWidgets.QPushButton(self.centralwidget)
        self.botao_alterar_tag_cartao.setGeometry(QtCore.QRect(675, 590, 230, 120))
        self.botao_alterar_tag_cartao.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 22pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(125, 131, 137);")
        self.botao_alterar_tag_cartao.setObjectName("botao_alterar_tag_cartao")
        self.botao_alterar_classe = QtWidgets.QPushButton(self.centralwidget)
        self.botao_alterar_classe.setGeometry(QtCore.QRect(380, 590, 230, 120))
        self.botao_alterar_classe.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 25pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(155, 228, 179);")
        self.botao_alterar_classe.setObjectName("botao_alterar_classe")
        self.label_imagem_patente = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_patente.setGeometry(QtCore.QRect(1150, 10, 120, 120))
        self.label_imagem_patente.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_imagem_patente.setText("")
        self.label_imagem_patente.setPixmap(QtGui.QPixmap("imagens/aprendiz_03.png"))
        self.label_imagem_patente.setScaledContents(True)
        self.label_imagem_patente.setObjectName("label_imagem_patente")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(80, 60, 1031, 121))
        self.lineEdit_nome.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.lineEdit_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_data_nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data_nascimento.setGeometry(QtCore.QRect(80, 230, 1031, 121))
        self.lineEdit_data_nascimento.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.lineEdit_data_nascimento.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_nascimento.setObjectName("lineEdit_data_nascimento")
        self.lineEdit_edv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_edv.setGeometry(QtCore.QRect(80, 400, 1031, 121))
        self.lineEdit_edv.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.lineEdit_edv.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_edv.setObjectName("lineEdit_edv")
        self.label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.label_Borda.setText("")
        self.label_Borda.setPixmap(QtGui.QPixmap("imagens/Borda.png"))
        self.label_Borda.setScaledContents(True)
        self.label_Borda.setObjectName("label_Borda")
        Editar_cadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Editar_cadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Editar_cadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Editar_cadastro)
        self.statusbar.setObjectName("statusbar")
        Editar_cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(Editar_cadastro)
        QtCore.QMetaObject.connectSlotsByName(Editar_cadastro)

    def retranslateUi(self, Editar_cadastro):
        _translate = QtCore.QCoreApplication.translate
        Editar_cadastro.setWindowTitle(_translate("Editar_cadastro", "MainWindow"))
        self.botao_cancelar.setText(_translate("Editar_cadastro", "CANCELAR"))
        self.botao_atualizar.setText(_translate("Editar_cadastro", "ATUALIZAR"))
        self.botao_alterar_tag_cartao.setText(_translate("Editar_cadastro", "ALTERAR TAG \n"
"DO CARTÃO"))
        self.botao_alterar_classe.setText(_translate("Editar_cadastro", "ALTERAR \n"
"CLASSE"))
        self.lineEdit_nome.setText(_translate("Editar_cadastro", "NOME"))
        self.lineEdit_data_nascimento.setText(_translate("Editar_cadastro", "DATA DE NASCIMENTO"))
        self.lineEdit_edv.setText(_translate("Editar_cadastro", "EDV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editar_cadastro = QtWidgets.QMainWindow()
    ui = Ui_Editar_cadastro()
    ui.setupUi(Editar_cadastro)
    Editar_cadastro.show()
    sys.exit(app.exec_())
