# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Relatos_liberacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Relatos_liberacao(object):
    def setupUi(self, Relatos_liberacao):
        Relatos_liberacao.setObjectName("Relatos_liberacao")
        Relatos_liberacao.resize(1290, 841)
        Relatos_liberacao.setMinimumSize(QtCore.QSize(1290, 841))
        Relatos_liberacao.setMaximumSize(QtCore.QSize(1290, 841))
        Relatos_liberacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        Relatos_liberacao.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Relatos_liberacao)
        self.centralwidget.setObjectName("centralwidget")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(20, 60, 881, 51))
        self.label_nome.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 16pt \"Bosch Sans Bold\";\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 207, 0);")
        self.label_nome.setObjectName("label_nome")
        self.label_fundo_branco = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_branco.setGeometry(QtCore.QRect(20, 97, 1251, 671))
        self.label_fundo_branco.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 12pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255,255,255);\n"
"")
        self.label_fundo_branco.setText("")
        self.label_fundo_branco.setObjectName("label_fundo_branco")
        self.label_fundo_preto = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_preto.setGeometry(QtCore.QRect(20, 20, 1251, 41))
        self.label_fundo_preto.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:1px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.label_fundo_preto.setText("")
        self.label_fundo_preto.setObjectName("label_fundo_preto")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(895, 60, 171, 51))
        self.label_data.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 18pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 207, 0);")
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.label_titulo_usuario = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_usuario.setGeometry(QtCore.QRect(380, 20, 171, 41))
        self.label_titulo_usuario.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 24pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_titulo_usuario.setObjectName("label_titulo_usuario")
        self.label_titulo_data = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_data.setGeometry(QtCore.QRect(923, 20, 111, 41))
        self.label_titulo_data.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 24pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_titulo_data.setObjectName("label_titulo_data")
        self.label_nao_conformidade = QtWidgets.QLabel(self.centralwidget)
        self.label_nao_conformidade.setGeometry(QtCore.QRect(70, 120, 311, 31))
        self.label_nao_conformidade.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 18pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(234, 229, 239);\n"
"color: rgb(237, 0, 7);")
        self.label_nao_conformidade.setObjectName("label_nao_conformidade")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.lineEdit_descricao = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_descricao.setGeometry(QtCore.QRect(410, 110, 851, 491))
        self.lineEdit_descricao.setStyleSheet("border-style: inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 14pt \"Bosch Sans Bold\";\n"
"\n"
"")
        self.lineEdit_descricao.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_descricao.setObjectName("lineEdit_descricao")
        self.label_fundo_branco_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_branco_2.setGeometry(QtCore.QRect(20, 97, 381, 671))
        self.label_fundo_branco_2.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 229, 239);")
        self.label_fundo_branco_2.setText("")
        self.label_fundo_branco_2.setObjectName("label_fundo_branco_2")
        self.label_titulo_periodo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_periodo.setGeometry(QtCore.QRect(1070, 20, 171, 41))
        self.label_titulo_periodo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 24pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_titulo_periodo.setObjectName("label_titulo_periodo")
        self.label_periodo = QtWidgets.QLabel(self.centralwidget)
        self.label_periodo.setGeometry(QtCore.QRect(1060, 60, 211, 51))
        self.label_periodo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 20pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 207, 0);")
        self.label_periodo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_periodo.setObjectName("label_periodo")
        self.botao_finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_finalizar.setGeometry(QtCore.QRect(950, 620, 271, 121))
        self.botao_finalizar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 30px;\n"
"\n"
"font: 75 30pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,136,74);")
        self.botao_finalizar.setObjectName("botao_finalizar")
        self.botao_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cancelar.setGeometry(QtCore.QRect(450, 620, 271, 121))
        self.botao_cancelar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 30px;\n"
"\n"
"font: 75 30pt \"Bosch Sans Bold\";\n"
"background-color: rgb(237, 0, 7);")
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.label_fundo_branco_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_branco_3.setGeometry(QtCore.QRect(397, 597, 874, 171))
        self.label_fundo_branco_3.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_fundo_branco_3.setText("")
        self.label_fundo_branco_3.setObjectName("label_fundo_branco_3")
        self.label_itens_nao_conformes = QtWidgets.QLabel(self.centralwidget)
        self.label_itens_nao_conformes.setGeometry(QtCore.QRect(30, 160, 361, 601))
        self.label_itens_nao_conformes.setStyleSheet("border-style: inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 14pt \"Bosch Sans Bold\";\n"
"background-color: rgb(234, 229, 239);\n"
"")
        self.label_itens_nao_conformes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_itens_nao_conformes.setObjectName("label_itens_nao_conformes")
        self.label_fundo_branco.raise_()
        self.lineEdit_descricao.raise_()
        self.label_fundo_branco_3.raise_()
        self.label_fundo_preto.raise_()
        self.label_titulo_usuario.raise_()
        self.label_titulo_data.raise_()
        self.Label_Borda.raise_()
        self.label_fundo_branco_2.raise_()
        self.label_nao_conformidade.raise_()
        self.label_titulo_periodo.raise_()
        self.label_periodo.raise_()
        self.botao_finalizar.raise_()
        self.botao_cancelar.raise_()
        self.label_nome.raise_()
        self.label_data.raise_()
        self.label_itens_nao_conformes.raise_()
        Relatos_liberacao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Relatos_liberacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Relatos_liberacao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Relatos_liberacao)
        self.statusbar.setObjectName("statusbar")
        Relatos_liberacao.setStatusBar(self.statusbar)

        self.retranslateUi(Relatos_liberacao)
        QtCore.QMetaObject.connectSlotsByName(Relatos_liberacao)

    def retranslateUi(self, Relatos_liberacao):
        _translate = QtCore.QCoreApplication.translate
        Relatos_liberacao.setWindowTitle(_translate("Relatos_liberacao", "MainWindow"))
        self.label_nome.setText(_translate("Relatos_liberacao", "NOME:"))
        self.label_data.setText(_translate("Relatos_liberacao", "00/00/0000"))
        self.label_titulo_usuario.setText(_translate("Relatos_liberacao", "USUÁRIO"))
        self.label_titulo_data.setText(_translate("Relatos_liberacao", "DATA"))
        self.label_nao_conformidade.setText(_translate("Relatos_liberacao", "NÃO CONFORMIDADE:"))
        self.lineEdit_descricao.setText(_translate("Relatos_liberacao", "TextLabel"))
        self.label_titulo_periodo.setText(_translate("Relatos_liberacao", "PERÍODO"))
        self.label_periodo.setText(_translate("Relatos_liberacao", "14:20"))
        self.botao_finalizar.setWhatsThis(_translate("Relatos_liberacao", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_finalizar.setText(_translate("Relatos_liberacao", "FINALIZAR"))
        self.botao_cancelar.setWhatsThis(_translate("Relatos_liberacao", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_cancelar.setText(_translate("Relatos_liberacao", "CANCELAR"))
        self.label_itens_nao_conformes.setText(_translate("Relatos_liberacao", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Relatos_liberacao = QtWidgets.QMainWindow()
    ui = Ui_Relatos_liberacao()
    ui.setupUi(Relatos_liberacao)
    Relatos_liberacao.show()
    sys.exit(app.exec_())
