# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standby.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Standby(object):
    def setupUi(self, Standby):
        Standby.setObjectName("Standby")
        Standby.resize(1290, 841)
        Standby.setMinimumSize(QtCore.QSize(1290, 841))
        Standby.setMaximumSize(QtCore.QSize(1290, 841))
        Standby.setStyleSheet("background-color: rgb(0, 0, 0);")
        Standby.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Standby)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_tag = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tag.setGeometry(QtCore.QRect(490, 280, 91, 20))
        self.lineEdit_tag.setStyleSheet("border-style: inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"font: 75 32pt \"Bosch Sans Bold\";\n"
"border-radius: 25px;\n"
"background-color: rgb(193, 199, 204);")
        self.lineEdit_tag.setObjectName("lineEdit_tag")
        self.botao_imagem = QtWidgets.QPushButton(self.centralwidget)
        self.botao_imagem.setGeometry(QtCore.QRect(300, 210, 761, 611))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Logo_Access_Control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_imagem.setIcon(icon)
        self.botao_imagem.setIconSize(QtCore.QSize(700, 700))
        self.botao_imagem.setObjectName("botao_imagem")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(100, 30, 1101, 131))
        self.label_titulo.setStyleSheet("font: 75 40pt \"Bosch Sans Bold\";\n"
"color: rgb(255, 255, 255);")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_preto = QtWidgets.QLabel(self.centralwidget)
        self.label_preto.setGeometry(QtCore.QRect(1000, 190, 71, 611))
        self.label_preto.setObjectName("label_preto")
        self.lineEdit_tag.raise_()
        self.label_titulo.raise_()
        self.botao_imagem.raise_()
        self.label_preto.raise_()
        Standby.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Standby)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Standby.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Standby)
        self.statusbar.setObjectName("statusbar")
        Standby.setStatusBar(self.statusbar)

        self.retranslateUi(Standby)
        QtCore.QMetaObject.connectSlotsByName(Standby)

    def retranslateUi(self, Standby):
        _translate = QtCore.QCoreApplication.translate
        Standby.setWindowTitle(_translate("Standby", "MainWindow"))
        self.lineEdit_tag.setText(_translate("Standby", "                  TAG DO CARTÃO"))
        self.botao_imagem.setText(_translate("Standby", "PushButton"))
        self.label_titulo.setText(_translate("Standby", "APROXIME O CRACHÁ \n"
"SOBRE O LEITOR"))
        self.label_preto.setText(_translate("Standby", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Standby = QtWidgets.QMainWindow()
    ui = Ui_Standby()
    ui.setupUi(Standby)
    Standby.show()
    sys.exit(app.exec_())
